Twitter feature
elagarrigue/AyDS22-AK-Lisboa3 pull request #7
Opened 2022-08-26 22:10 UTC by ThiagoZanconi

2022-08-26 22:16 UTC, ThiagoZanconi commented
Dejo la descripcion del PR aca abajo (Aprete enter e hizo el PR de una):

TwitterFeature:
-Implementacion de boton "View tweets from artist" que muestra tweets sobre el artista de la cancuion buscada.
-Patron arquitectonico: MVI
-Patrones de diseño utilizados:
--Observer, para comunicar reducer con view
--Reducer, para modificar el estado de la view
--Presenter, como intermediario de comunicacion entre view, modelo y reducer
--Repository: Con request a servicio externo y cache de datos local
-Tests: Implementacion de tests de las clases mas importantes
--(Me quedo sin funcionar el caso del repository en el que el servicio externo devuelve una excepcion

2022-08-28 20:15 UTC, ThiagoZanconi commented
Ya encontre el error del caso de test en el ArtistTweetsRepositoryTest. En realidad en la clase ArtistTweetsRepository me habia comido el try catch en la llamada al servicio externo.

2022-08-28 20:18 UTC, ThiagoZanconi commented
No se si commitear ese cambio o esperar a que hagas el review del PR.

2022-08-29 16:48 UTC, elagarrigue commented
Hacé el commit sí. Voy a tratar de hacer el review hoy.

2022-08-30 17:54 UTC, elagarrigue requested changes
Está muy bien en general, sólo comentarios menores y par de tests por arreglar

2022-08-30 17:54 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/artisttweets/model/repository/TimeWrapper.kt
> +interface TimeWrapper{
esta clase podría estar en utils

2022-08-30 17:54 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/artisttweets/model/repository/TweetsRepository.kt
> +        if(timeWrapper.getCurrentTimeInMilliS()-lastRefreshDate>EXTERNAL_SERVICE_REFRESH_GAP){
por nivel de abstracción, la evaluación de la condición debería estar en una sub función, para que quede más legible

2022-08-30 17:54 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/artisttweets/model/repository/TweetsRepository.kt
> +                    lastRefreshDate=timeWrapper.getCurrentTimeInMilliS()
diferente nivel de abstracción, mover a una función

2022-08-30 17:54 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/artisttweets/model/repository/local/twitter/TweetsCache.kt
> +    fun insertTweets(query: String, tweets: List<Tweet>)
en realidad está sobre escribiendo la lista, no agregando. Mejor llamarla `replaceTweets`

2022-08-30 17:54 UTC, elagarrigue commented on app/src/test/java/ayds/lisboa/songinfo/artisttweets/intent/ArtistTweetsPresenterTest.kt
> +    fun `given artist name should return tweet list from model to reducer`(){
Este test falla

2022-08-30 17:54 UTC, elagarrigue commented on app/src/test/java/ayds/lisboa/songinfo/artisttweets/model/repository/TweetsRepositoryTest.kt
> +    fun `given existing artist without a 10 second difference on last refresh should return the tweet list it in the cache`(){
Este test falla

2022-08-30 18:47 UTC, ThiagoZanconi commented
Dale, seguramente hoy a la noche haga las correcciones. Creo que los tests me habia olvidado de cambiarlos despues de hacer cambio del observer que te pregunte.

2022-08-30 23:38 UTC, ThiagoZanconi commented on app/src/test/java/ayds/lisboa/songinfo/artisttweets/model/repository/TweetsRepositoryTest.kt
> +    fun `given existing artist without a 10 second difference on last refresh should return the tweet list it in the cache`(){
A mi este test no me falla. Recien hice el refactor del repository, pero no deberia haber cambiado nada, era todo extraer funciones.

2022-08-31 21:31 UTC, elagarrigue commented on app/src/test/java/ayds/lisboa/songinfo/artisttweets/model/repository/TweetsRepositoryTest.kt
> +    fun `given existing artist without a 10 second difference on last refresh should return the tweet list it in the cache`(){
ya no falla, se ve que faltaba hacer un push

2022-08-31 21:31 UTC, elagarrigue approved these changes

2022-09-01 21:09 UTC, merged